[theme]
base="light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true


[postinstall]
commands = [
  "python -m spacy download en_core_web_sm"
]
